name: update-twikoo-js

on: 
  workflow_dispatch:

jobs:
  update-twikoo-js:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Latest JS and Edit
        run: |
          rm -rf source/js/plugins/twikoo.min.js
          curl -o source/js/plugins/twikoo.min.js -L https://unpkg.com/twikoo/dist/twikoo.min.js
          sed -i 's/64,158,255/13,86,97/Ig' source/js/plugins/twikoo.min.js
          sed -i 's/a0cfff/33a6b8/Ig' source/js/plugins/twikoo.min.js
          sed -i 's/409eff/0089a7/Ig' source/js/plugins/twikoo.min.js
          sed -i 's/3a8ee6/0d5661/Ig' source/js/plugins/twikoo.min.js
          sed -i 's/c6e2ff/0d56614f/Ig' source/js/plugins/twikoo.min.js
          sed -i 's/ecf5ff/0d56610f/Ig' source/js/plugins/twikoo.min.js
          sed -i 's/dcdfe6/dce5e6/Ig' source/js/plugins/twikoo.min.js
      
      - name: Push
        run: |
          git config --global user.email "aquausora@outlook.com"
          git config --global user.name "aquausora"
          git add .
          git commit -m "update twikoo.min.js"
          git pull
          git push
